# -*- coding: utf-8 -*-
"""financial inclusion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X-UZua7JHkIirdmvZSDCoE957rg9Uys3
"""

# import libs

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


data_set = pd.read_csv('http://bit.ly/FinancialDataset')
# data_set.head(5)
# data_set.tail()
data_set.describe()
# data_set.isnull()
# data_set.shape
# data_set.columns
final_data = data_set['The relathip with head'].unique()
print(len(final_data))

data_set.dropna(inplace=True)
# plotting a histogram uning matplotlib and seaborn
# 
plt.figure(figsize = (20, 15))
sns.distplot(data_set['Respondent Age'], color="red")
plt.title("Distribution of respondents age")
plt.xlabel("Respondent age")
plt.ylabel("Frequency")
plt.show()


plt.figure(figsize=(8,5))
sns.countplot(data_set['country'])
plt.title("Countries")
plt.xlabel("Country name")
plt.ylabel("population")
plt.show()

# marital status
plt.figure(figsize=(8,5))
sns.countplot(data_set['marital_status'])
plt.title("Marital status")
plt.xlabel("Status")
plt.ylabel("population")
plt.show()

